language: c

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.2

branches:
  only:
    - dev

install:
  - bash .travis/setup_lua.sh

notifications:
  email:
    on_success: change
    on_failure: always

