language: c

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.2

branches:
  only:
    - dev

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo luarocks make pegasus-0.0.1-5.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

notifications:
  email:
    on_success: change
    on_failure: always

