language: c

matrix:
  include:
    - env: LUA="lua 5.1"
      os: osx
    - env: LUA="lua 5.1"
      os: linux
    - env: LUA="lua 5.2"
      os: linux
    - env: LUA="lua 5.3"
      os: linux
    - env: LUA="luajit 2.0"
      os: linux
    - env: LUA="luajit 2.1"
      os: linux

env:
  global:
    - LUAROCKS_BASE=luarocks-2.2.1

before_install:
  - sudo apt-get update
  - sudo apt-get install $LUA
  - sudo apt-get install $LUA_DEV
  - lua$LUA_SFX -v
  # Install a recent luarocks release
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - cd $LUAROCKS_BASE
  - ./configure
    --lua-version=$LUA_VER --lua-suffix=$LUA_SFX --with-lua-include="$LUA_INCDIR"
  - sudo make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

install:
  - sudo -E luarocks install busted
  - sudo -E luarocks install mimetypes
  - sudo -E luarocks install luasocket
  - sudo -E luarocks install luacov
  - sudo -E luarocks install luafilesystem
  - sudo -E luarocks install lzlib

script:
  - sudo -E busted
