language: c

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

branches:
  only:
    - dev

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls
  - sudo luarocks install Lua-cURL --server=https://rocks.moonscript.org/dev
  - sudo luarocks install luacov-coveralls --server=https://rocks.moonscript.org/dev
  - sudo luarocks install lunitx
  - sudo make install

install:
  - sudo luarocks make pegasus-0.0.1-5.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script:
  - make test

notifications:
  email:
    on_success: change
    on_failure: always

